const MessageBoxConstant  = [
  {//scene:b
    param:'1',
    message:"俺と、、、、、結婚してくれ。",
    who:"かれぴ",
    overview:""
  },
  {//scene:b
    param:'2',
    message:"お前を悪いようにはしない。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'3',
    message:"だから・・・・だから、お願いだ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'4',
    message:"ぽっ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'5',
    message:"・・・・・。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'6',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'7',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'8',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'9',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'10',
    message:"いい夢見てたようだね。結婚する夢でも見てたのか？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'11',
    message:"夢の中で俺以外の人間と結婚するなんて許・さ・な・い",
    who:"かれぴ",
    overview:""
  },
  {
    param:'12',
    message:"うなされてたけど大丈夫？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'13',
    message:"料理つくるからこのまま寝てていいよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'14',
    message:"ご飯つくったよ。食べよう。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'15',
    message:"いただきます。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'16',
    message:"（あれ・・・ドレッシングがないゾ。）",
    who:"心の声",
    overview:""
  },
  {
    param:'17',
    message:"お前は俺がいないとダメだなあ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'18',
    message:"おいしいね。",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'19',
    message:"はいどうぞ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'20',
    message:"....",
    who:"かれぴ",
    overview:""
  },
  {
    param:'21',
    message:"ごちそうさま。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'22',
    message:"仕事にいってらっしゃい。くれぐれも気をつけて。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'23',
    message:"今日の門限は19:00だぞ。絶対遅れるなよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'24',
    message:"そろそろ仕事に行かなきゃだね。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'25',
    message:"気をつけてね。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'26',
    message:"あ、ゴミ出しもしておいたから。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'27',
    message:"いってらっしゃい。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'28',
    message:"嬉しいな。一緒につくろう",
    who:"かれぴ",
    overview:""
  },
  {
    param:'29',
    message:"じゅーじゅー",
    who:"効果音",
    overview:""
  }, 
  {
    param:'30',
    message:"よし。できた",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'31',
    message:"よし。たべよう。いただきます。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'32',
    message:"美味しいねー",
    who:"かれぴ",
    overview:""
  },
  {
    param:'33',
    message:"あのさ、今日大事な話があるんだけど、早く帰ってこれる？",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'34',
    message:"やったー！ありがとう。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'35',
    message:"じゃあ楽しみに待ってるね！仕事頑張って。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'36',
    message:"残念・・・。わかったよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'37',
    message:"気をつけていってらっしゃい。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'38',
    message:"（はぁ・・別れたいなぁ・・・束縛辛い。）",
    who:"心の声",
    overview:""
  },
  {
    param:'39',
    message:"バイブの音（ブーブー）",
    who:"携帯",
    overview:""
  },
  {
    param:'40',
    message:"**寄り道はダメだ。門限を忘れんなよ。**",
    who:"かれぴのLINE",
    overview:""
  },
  {
    param:'41',
    message:"（怖いよ。）",
    who:"心の声",
    overview:""
  },
  {
    param:'42',
    message:"（かれぴは、優しくてなんでもやってくれる。楽だな〜）",
    who:"心の声",
    overview:""
  },
  {
    param:'43',
    message:"（早く帰れるようにがんばろう。）",
    who:"心の声",
    overview:""
  },
  {
    param:'44',
    message:"バイブの音（ブーブー）",
    who:"携帯",
    overview:""
  },
  {
    param:'45',
    message:"**やっと家でた？今から合流！**",
    who:"浮気相手のLINE",
    overview:""
  },
  {
    param:'46',
    message:"**今から向かうねネ**",
    who:"浮気相手のLINE",
    overview:""
  },
  {
    param:'47',
    message:"会社に到着",
    who:"ナレーション",
    overview:""
  },
  {
    param:'48',
    message:"今日、営業ペアだからよろしくー",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'49',
    message:"あ、よろしくお願いします。",
    who:"わたし",
    overview:""
  },
  {
    param:'50',
    message:"今日も暑いなーがんばろうなー",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'51',
    message:"(ダッダッダッダッ・・)",
    who:"効果音",
    overview:""
  },
  {
    param:'52',
    message:"(ドン！！！！！)",
    who:"効果音",
    overview:""
  },
  {
    param:'53',
    message:"せ、先輩、はやくいきましょう！",
    who:"わたし",
    overview:""
  },
  {
    param:'54',
    message:"お疲れ。途中から元気なくなってたけど無理すんなし",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'55',
    message:"(帰るのが怖い)",
    who:"心の声",
    overview:""
  },
  {
    param:'56',
    message:"(永遠に着かなければいいのに)",
    who:"心の声",
    overview:""
  },
  {
    param:'57',
    message:"おかえり。遅かったな門限過ぎてるぞ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'58',
    message:"楽しそうに、男と歩いてたなー",
    who:"かれぴ",
    overview:""
  },
  {
    param:'59',
    message:"悪い子には、お・仕・置・き・だ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'60',
    message:"ドンッ（殴る音）",
    who:"効果音",
    overview:""
  },
  {
    param:'61',
    message:"お前が、悪いんだ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'62',
    message:"あ、しまったハンカチ忘れた。",
    who:"わたし",
    overview:""
  },
  {
    param:'63',
    message:"**ハンカチ忘れたから持ってきて。**",
    who:"かれぴのLINE",
    overview:""
  },
  {
    param:'64',
    message:"**わかりました。**",
    who:"かれぴのLINE",
    overview:""
  },
  {
    param:'65',
    message:"おまたせ。持ってきたよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'66',
    message:"さようなら。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'67',
    message:"（仕事に戻るか）",
    who:"心の中",
    overview:""
  },
  {
    param:'68',
    message:"やっと仕事終わった。かれぴにLINEしよう。",
    who:"わたし",
    overview:""
  },
  {
    param:'69',
    message:"**残業になったのでご飯つくって先寝てて。**",
    who:"かれぴのLINE",
    overview:""
  },
  {
    param:'70',
    message:"(あれ、暗いぞ。あー寝たのか。)",
    who:"心の声",
    overview:""
  },
  {
    param:'71',
    message:"あれ？なんか貼ってあるぞ？",
    who:"わたし",
    overview:""
  },
  {
    param:'72',
    message:"さようなら　かれぴ",
    who:"置き手紙",
    overview:""
  },
  {
    param:'73',
    message:"・・・・",
    who:"わたし",
    overview:""
  },
  {
    param:'74',
    message:"飯ぐらいつくってから別れろや",
    who:"わたし",
    overview:""
  },
  {
    param:'75',
    message:"やっとヤレるね",
    who:"浮気相手",
    overview:""
  },
  {
    param:'76',
    message:"かれぴよりあなたの方が相性がイイわ❤︎",
    who:"わたし",
    overview:""
  },
  {
    param:'77',
    message:"（よし、会社に到着！）",
    who:"心の声",
    overview:""
  },
  {
    param:'78',
    message:"（うわあ嫌な上司が来た・・）",
    who:"心の声",
    overview:""
  },
  {
    param:'79',
    message:"気分次第で意地悪を言ってくるのがとても嫌",
    who:"ナレーター",
    overview:""
  },
  {
    param:'80',
    message:"おい、今日残業してでもこの仕事をやりきれよ",
    who:"嫌な上司",
    overview:""
  },
  {
    param:'81',
    message:"当たり前だよな。言ったからには、やれよ。",
    who:"嫌な上司",
    overview:""
  },
  {
    param:'82',
    message:"すっかり、遅くなっちゃった。タクシー使おうかな・・？",
    who:"わたし",
    overview:""
  },
  {
    param:'83',
    message:"何言ってるんだ？お前には一切、仕事を頼まん！",
    who:"嫌な上司",
    overview:""
  },
  {
    param:'84',
    message:"お金ももったいないし我慢するか。",
    who:"わたし",
    overview:""
  },
  {
    param:'85',
    message:"(サッサッサッサ)",
    who:"効果音",
    overview:""
  },
  {
    param:'86',
    message:"え？だれ？こわい",
    who:"わたし",
    overview:""
  },
  {
    param:'87',
    message:"グサッ（ナイフが腹部を突き抜け内蔵をえぐる音）",
    who:"効果音",
    overview:""
  },
  {
    param:'88',
    message:"タクシーで帰ろう",
    who:"心の声",
    overview:""
  },
  {
    param:'89',
    message:"あれ？家に誰もいない",
    who:"わたし",
    overview:""
  },
  {
    param:'90',
    message:"よし、サプライズでかれぴっぴの家に突撃じゃ",
    who:"わたし",
    overview:""
  },
  {
    param:'91',
    message:"しつれいしまーす(ガチャッ)",
    who:"わたし",
    overview:""
  },
  {
    param:'92',
    message:"きゃあああああ浮気ーーー",
    who:"わたし",
    overview:""
  },
  {
    param:'93',
    message:"(今日は遅いし我慢するか)",
    who:"心の声",
    overview:""
  },
  {
    param:'94',
    message:"次の日のニュースでかれぴが帰らぬ人になってしまったことを知った。",
    who:"ナレーション",
    overview:""
  },
  {
    param:'95',
    message:"（はぁ言ってしまったけどこれでいいんだ）",
    who:"心の声",
    overview:""
  },
  {
    param:'96',
    message:"頑張ったね。今夜空いてる？",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'97',
    message:"じゃあ、よろしくね。",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'98',
    message:"そっか。じゃあね。",
    who:"イケメンの先輩",
    overview:""
  },
  {
    param:'99',
    message:"はぁ、やっと帰れる。かれぴの大事な話ってなんだろう。",
    who:"わたし",
    overview:""
  },
  {
    param:'100',
    message:"おかえり",
    who:"かれぴ",
    overview:""
  },
  {
    param:'101',
    message:"あの、大事な話なんだけど・・・",
    who:"かれぴ",
    overview:""
  },
  {
    param:'102',
    message:"・・・",
    who:"かれぴ",
    overview:""
  },
  {
    param:'102',
    message:"・・・",
    who:"かれぴ",
    overview:""
  },
  {
    param:'103',
    message:"俺と、、、、、結婚してくれ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'104',
    message:"お前を悪いようにはしない。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'105',
    message:"だから・・・・だから、お願いだ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'106',
    message:"ぽっ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'107',
    message:"・・・・・。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'108',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'109',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'110',
    message:"いい夢見てたようだね。結婚した夢でも見てたのか？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'111',
    message:"って結婚したじゃん（笑",
    who:"かれぴ",
    overview:""
  },
  {
    param:'112',
    message:"朝食準備するから起きてきてね！",
    who:"かれぴ",
    overview:""
  },
  {
    param:'113',
    message:"ふぁあ　眠いや　おはよう",
    who:"わたし",
    overview:""
  },
  {
    param:'114',
    message:"おはよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'115',
    message:"朝食できてるよ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'116',
    message:"・・・・・。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'117',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'118',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'119',
    message:"うなされてたけど大丈夫？",
    who:"かれぴ",
    overview:""
  },
  
]

export default MessageBoxConstant