const MessageBoxConstant  = [
  {//scene:b
    param:'1',
    message:"俺と、、、、、結婚してくれ。",
    who:"かれぴ",
    overview:""
  },
  {//scene:b
    param:'2',
    message:"お前を悪いようにはしない。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'3',
    message:"だから・・・・だから、お願いだ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'4',
    message:"ぽっ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'5',
    message:"・・・・・。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'6',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'7',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'8',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'9',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'10',
    message:"いい夢見てたようだね。結婚する夢でも見てたのか？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'11',
    message:"夢の中で俺以外の人間と結婚するなんて許・さ・な・い",
    who:"かれぴ",
    overview:""
  },
  {
    param:'12',
    message:"うなされてたけど大丈夫？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'13',
    message:"料理つくるからこのまま寝てていいよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'14',
    message:"ご飯つくったよ。食べよう。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'15',
    message:"いただきます。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'16',
    message:"（あれ・・・ドレッシングがないゾ。）",
    who:"回想",
    overview:""
  },
  {
    param:'17',
    message:"お前は俺がいないとダメだなあ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'18',
    message:"おいしいね。",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'19',
    message:"はいどうぞ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'20',
    message:"....",
    who:"かれぴ",
    overview:""
  },
  {
    param:'21',
    message:"ごちそうさま。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'22',
    message:"仕事にいってらっしゃい。くれぐれも気をつけて。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'23',
    message:"今日の門限は19:00だぞ。絶対遅れるなよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'24',
    message:"そろそろ仕事に行かなきゃだね。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'25',
    message:"気をつけてね。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'26',
    message:"あ、ゴミ出しもしておいたから。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'27',
    message:"いってらっしゃい。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'28',
    message:"嬉しいな。一緒につくろう",
    who:"かれぴ",
    overview:""
  },
  {
    param:'29',
    message:"じゅーじゅー",
    who:"効果音",
    overview:""
  }, 
  {
    param:'30',
    message:"よし。できた",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'31',
    message:"よし。たべよう。いただきます。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'32',
    message:"美味しいねー",
    who:"かれぴ",
    overview:""
  },
  {
    param:'33',
    message:"あのさ、今日大事な話があるんだけど、早く帰ってこれる？",
    who:"かれぴ",
    overview:""
  }, 
  {
    param:'34',
    message:"やったー！ありがとう。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'35',
    message:"じゃあ楽しみに待ってるね！仕事頑張って。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'36',
    message:"残念・・・。わかったよ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'37',
    message:"気をつけていってらっしゃい。",
    who:"かれぴ",
    overview:""
  },
]

export default MessageBoxConstant