const MessageBoxConstant  = [
  {//scene:b
    param:'1',
    message:"俺と、、、、、結婚してくれ。",
    who:"かれぴ",
    overview:""
  },
  {//scene:b
    param:'2',
    message:"お前を悪いようにはしない。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'3',
    message:"だから・・・・だから、お願いだ。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'4',
    message:"ぽっ",
    who:"かれぴ",
    overview:""
  },
  {
    param:'5',
    message:"・・・・・。",
    who:"かれぴ",
    overview:""
  },
  {
    param:'6',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'7',
    message:"おい、おい！！！",
    who:"？？？",
    overview:""
  },
  {
    param:'8',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'9',
    message:"起きろ！いつまで寝てるんだ？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'10',
    message:"いい夢見てたようだね。結婚する夢でも見てたのか？",
    who:"かれぴ",
    overview:""
  },
  {
    param:'11',
    message:"夢の中で俺以外の人間と結婚するなんて許・さ・な・い",
    who:"かれぴ",
    overview:""
  },
  {
    param:'12',
    message:"うなされてたけど大丈夫？",
    who:"かれぴ",
    overview:""
  }
]

export default MessageBoxConstant