//ストーリ
const TriggerConstant  = [
  {
    triggerId:'0',
    triggerType:"0",
    nextGameButtonParam:"1",
    nextScreenParam:"1",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'1',
    triggerType:"button",
    nextGameButtonParam:"0",
    nextScreenParam:"2",
    nextMessageBoxParam:"1",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'1',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"2",
    nextMessageBoxParam:"2",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'2',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"2",
    nextMessageBoxParam:"3",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'3',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"2",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"1"
  },
  {//================================
  //●夢かれぴに嫉妬=====================
  //==================================
    triggerId:'1000',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"3",
    nextMessageBoxParam:"4",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'4',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"3",
    nextMessageBoxParam:"6",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'6',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"8",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'8',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"10",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'10',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"7",
    nextMessageBoxParam:"11",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'11',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"7",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
    //==============================
    //●夢かれぴに嫉妬-終了=============
    //==============================
  },
  {
    triggerId:'1001',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"4",
    nextMessageBoxParam:"5",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'5',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"4",
    nextMessageBoxParam:"7",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'7',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"9",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'9',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"12",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'12',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"13",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'13',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"2"
  },
  //==============================
  //●ルートB=======================
  //==============================
  {
    triggerId:'1003',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"8",
    nextMessageBoxParam:"14",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'14',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"15",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'15',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"16",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'16',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"3"
  },
  //==============================
  //●DV END=======================
  //==============================
  {
    triggerId:'1004',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"10",
    nextMessageBoxParam:"17",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'17',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"10",
    nextMessageBoxParam:"19",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'19',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"20",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'20',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"21",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'21',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"11",
    nextMessageBoxParam:"22",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'22',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"11",
    nextMessageBoxParam:"23",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'23',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"14",
    nextMessageBoxParam:"38",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'38',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"14",
    nextMessageBoxParam:"39",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'39',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"15",
    nextMessageBoxParam:"40",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'40',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"15",
    nextMessageBoxParam:"41",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'41',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"47",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'47',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"48",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'48',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"49",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'49',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"19",
    nextMessageBoxParam:"50",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'50',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"19",
    nextMessageBoxParam:"51",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'51',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"20",
    nextMessageBoxParam:"52",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'52',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"20",
    nextMessageBoxParam:"53",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'53',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"54",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'54',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"55",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'55',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"56",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'56',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"57",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'57',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"58",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'58',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"59",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'59',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"22",
    nextMessageBoxParam:"60",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'60',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"22",
    nextMessageBoxParam:"61",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'61',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"22",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  //==============================
  //●置き手紙END=======================
  //==============================
  {
    triggerId:'1005',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"24",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'24',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"11",
    nextMessageBoxParam:"25",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'25',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"12",
    nextMessageBoxParam:"26",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'26',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"12",
    nextMessageBoxParam:"27",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'26',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"12",
    nextMessageBoxParam:"27",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'27',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"14",
    nextMessageBoxParam:"42",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'42',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"62",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'62',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"23",
    nextMessageBoxParam:"63",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'63',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"23",
    nextMessageBoxParam:"64",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'64',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"24",
    nextMessageBoxParam:"65",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'65',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"24",
    nextMessageBoxParam:"66",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'66',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"67",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'67',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"68",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'68',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"25",
    nextMessageBoxParam:"69",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'68',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"25",
    nextMessageBoxParam:"69",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'69',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"70",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'70',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"71",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'71',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"27",
    nextMessageBoxParam:"72",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'72',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"27",
    nextMessageBoxParam:"73",
    nextSelectButtonParam:"0"
  }, 
  {
    triggerId:'73',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"27",
    nextMessageBoxParam:"74",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'74',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"27",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },

  //==============================
  //●ルートA=======================
  //==============================
  {
    triggerId:'1002',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"28",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'28',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"13",
    nextMessageBoxParam:"29",
    nextSelectButtonParam:"0"
  }, 
  {
    triggerId:'29',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"13",
    nextMessageBoxParam:"30",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'30',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"31",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'31',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"32",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'32',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"33",
    nextSelectButtonParam:"0"
  },  
  {
    triggerId:'33',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"4"
  },
  //==============================
  //●ルートC=======================
  //==============================
  {
    triggerId:'1006',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"34",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'34',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"11",
    nextMessageBoxParam:"35",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'35',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"14",
    nextMessageBoxParam:"43",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'43',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"77",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'77',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"78",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'78',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"79",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'79',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"29",
    nextMessageBoxParam:"80",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'80',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"29",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"5"
  },
  //==============================
  //●ルートE=======================
  //==============================
  {
    triggerId:'1008',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"29",
    nextMessageBoxParam:"81",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'81',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"82",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'82',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"6"
  },
  //==============================
  //●ルートG=======================
  //==============================
  {
    triggerId:'1010',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"31",
    nextMessageBoxParam:"88",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'88',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"89",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'89',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"7"
  },
  //==============================
  //●かれぴの浮気エンド==============
  //==============================
  {
    triggerId:'1012',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"90",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'90',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"91",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'91',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"32",
    nextMessageBoxParam:"92",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'92',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"32",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  //==============================
  //●かれぴの事故エンド==============
  //==============================
  {
    triggerId:'1013',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"26",
    nextMessageBoxParam:"93",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'93',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"33",
    nextMessageBoxParam:"94",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'94',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"33",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  
  //==============================
  //●殺害エンド=======================
  //==============================
  {
    triggerId:'1011',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"84",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'84',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"85",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'85',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"30",
    nextMessageBoxParam:"86",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'86',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"30",
    nextMessageBoxParam:"87",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'87',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"30",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  //==============================
  //●ルートF=======================
  //==============================
  {
    triggerId:'1009',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"29",
    nextMessageBoxParam:"83",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'83',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"17",
    nextMessageBoxParam:"95",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'95',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"96",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'96',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"8"
  },
  //==============================
  //●ルートH=======================
  //==============================
  {
    triggerId:'1015',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"98",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'98',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"21",
    nextMessageBoxParam:"99",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'99',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"100",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'100',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"101",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'101',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"102",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'102',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"103",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'103',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"104",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'104',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"105",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'105',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"34",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"9"
  },
  //==============================
  //●trueエンド====================
  //==============================
  {
    triggerId:'1016',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"35",
    nextMessageBoxParam:"106",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'106',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"35",
    nextMessageBoxParam:"107",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'107',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"35",
    nextMessageBoxParam:"108",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'107',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"35",
    nextMessageBoxParam:"108",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'108',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"109",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'109',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"110",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'110',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"111",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'111',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"112",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'112',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"113",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'113',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"114",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'114',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"115",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'115',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"1",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },

  //==============================
  //●無限ループEND==================
  //==============================
  {
    triggerId:'1017',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"36",
    nextMessageBoxParam:"116",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'116',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"36",
    nextMessageBoxParam:"117",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'117',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"5",
    nextMessageBoxParam:"118",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'118',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"119",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'119',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"6",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
  //==============================
  //●浮気END=======================
  //==============================
  {
    triggerId:'1014',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"18",
    nextMessageBoxParam:"97",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'97',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"28",
    nextMessageBoxParam:"75",
    nextSelectButtonParam:"0"
  },

  //==============================
  //●浮気END=======================
  //==============================
  {
    triggerId:'1007',
    triggerType:"selectButton",
    nextGameButtonParam:"0",
    nextScreenParam:"9",
    nextMessageBoxParam:"36",
    nextSelectButtonParam:"0"
  },  
  {
    triggerId:'36',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"12",
    nextMessageBoxParam:"37",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'37',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"14",
    nextMessageBoxParam:"44",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'44',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"16",
    nextMessageBoxParam:"45",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'45',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"16",
    nextMessageBoxParam:"46",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'46',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"28",
    nextMessageBoxParam:"75",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'75',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"28",
    nextMessageBoxParam:"76",
    nextSelectButtonParam:"0"
  },
  {
    triggerId:'76',
    triggerType:"messageBox",
    nextGameButtonParam:"0",
    nextScreenParam:"28",
    nextMessageBoxParam:"0",
    nextSelectButtonParam:"0"
  },
]

export default TriggerConstant